name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        module load BuildEnv/gcc-12.2.0.lua;
        # TODO add build statge for project

    - name: Test
      run: |
        module load BuildEnv/gcc-12.2.0.lua;
        # TODO: add project specific tests
